import { MapTiles } from "../components/MapTiles";
import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { MapContainer, Tooltip, Polyline, Marker, Popup, ZoomControl, useMap } from 'react-leaflet';
import { divIcon, latLngBounds } from 'leaflet';
import type { CashflowCheck, Chain, Load, TruckProfile } from '../types';
import { balanceColor } from '../money';
import raw from '../mocks/run-samples.json';

// Fixed preview responses generated by the existing backend's pure calculations.
// This entry point imports no API client and cannot create a Nessie transaction.
const data = raw as unknown as { profile: TruckProfile; boardCount: number; loads: Load[]; runs: { chain: Chain; cash: CashflowCheck; success: CashflowCheck }[] };
const money = (n: number) => n.toLocaleString('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2 });
const day = (iso: string) => new Date(`${iso.slice(0,10)}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
type State = 'ready' | 'planned' | 'shortfall' | 'confirmation' | 'success' | 'loading' | 'error' | 'unavailable';
function Icon({ name, size = 20 }: { name: 'route' | 'truck' | 'wallet' | 'pin' | 'arrow' | 'check' | 'close' | 'alert' | 'chevron' | 'layers'; size?: number }) {
  const paths: Record<typeof name, ReactNode> = {
    route: <><circle cx="6" cy="5" r="2"/><circle cx="18" cy="19" r="2"/><path d="M6 7v6a3 3 0 0 0 3 3h6a3 3 0 0 0 0-6h-3"/></>,
    truck: <><path d="M3 6h11v11H3zM14 10h4l3 4v3h-7"/><circle cx="7" cy="18" r="2"/><circle cx="17" cy="18" r="2"/></>,
    wallet: <><rect x="3" y="6" width="18" height="14" rx="3"/><path d="M17 11h4v5h-4a2.5 2.5 0 0 1 0-5M4 6V4h13"/></>,
    pin: <><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,
    arrow: <path d="M5 12h14m-6-6 6 6-6 6"/>,
    check: <path d="m5 12 4 4 10-10"/>, close: <path d="m6 6 12 12M18 6 6 18"/>,
    alert: <><circle cx="12" cy="12" r="9"/><path d="M12 7v6m0 3v1"/></>,
    chevron: <path d="m8 5 7 7-7 7"/>, layers: <><path d="m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
function useMobile() {
  const [mobile, setMobile] = useState(() => matchMedia('(max-width: 700px)').matches);
  useEffect(() => { const q = matchMedia('(max-width: 700px)'); const update = () => setMobile(q.matches); q.addEventListener('change', update); return () => q.removeEventListener('change', update); }, []);
  return mobile;
}
function FitMap({ chain, mobile, recenter }: { chain?: Chain; mobile: boolean; recenter: number }) {
  const map = useMap();
  useEffect(() => {
    map.invalidateSize({ animate: false });
    if (!chain) { map.setView([37.271, -79.9414], 8, { animate: false }); return; }
    const points: [number, number][] = chain.loads.flatMap(id => { const l = data.loads.find(x => x.id === id)!; return [[l.origin.lat!, l.origin.lng!], [l.destination.lat!, l.destination.lng!]]; });
    map.fitBounds(latLngBounds(points), { animate: false, paddingTopLeft: mobile ? [35, 110] : [445, 110], paddingBottomRight: mobile ? [35, 310] : [95, 100], maxZoom: 9 });
  }, [map, chain, mobile, recenter]);
  return null;
}
function Modal({ open, onClose, title, children, className = '' }: { open: boolean; onClose: () => void; title: string; children: ReactNode; className?: string }) {
  const ref = useRef<HTMLDialogElement>(null);
  const previous = useRef<HTMLElement | null>(null);
  useEffect(() => {
    if (open && !ref.current?.open) { previous.current = document.activeElement as HTMLElement; ref.current?.showModal(); }
    else if (!open && ref.current?.open) { ref.current.close(); const target = previous.current?.isConnected ? previous.current : document.querySelector<HTMLElement>('dialog[open] button, .run-selector button[aria-pressed="true"], .expand-button'); target?.focus(); }
  }, [open]);
  return <dialog ref={ref} className={`modal ${className}`} aria-label={title} onCancel={e => { e.preventDefault(); onClose(); }}>
    <div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label={`Close ${title}`} onClick={onClose} autoFocus><Icon name="close"/></button></div>{children}
  </dialog>;
}
export function MapsPreview() {
  const mobile = useMobile();
  const [state, setState] = useState<State>('ready');
  const [selected, setSelected] = useState(0);
  const [expanded, setExpanded] = useState(false);
  const [info, setInfo] = useState(false);
  const [announcement, setAnnouncement] = useState('');
  const [tilesUnavailable, setTilesUnavailable] = useState(false);
  const [recenter, setRecenter] = useState(0);
  const expandButton = useRef<HTMLButtonElement>(null);
  const run = data.runs[selected];
  const hasRun = ['planned', 'shortfall', 'confirmation', 'success'].includes(state);
  const hasCash = hasRun && state !== 'planned';
  const cash = state === 'success' ? run.success : run.cash;
  const offer = run.cash.advance_offer;
  useEffect(() => { if (!mobile) setExpanded(false); }, [mobile]);
  function show(next: State) { setState(next); setAnnouncement(next === 'shortfall' ? 'Three runs available. Selected run has a projected shortfall.' : next === 'success' ? 'Advance preview applied. No deposit was created.' : ''); }
  function selectRun(i: number) { setSelected(i); show('shortfall'); }
  function collapse() { setExpanded(false); requestAnimationFrame(() => expandButton.current?.focus()); }
  const heading = hasRun ? 'Runs' : 'Plan run';
  const panel = () => <>
    <div className="panel-intro"><span className="eyebrow">{hasRun ? 'ROANOKE ROUND TRIP' : 'STARTING FROM'}</span><h1>{hasRun ? heading : data.profile.current_location.city}</h1><p>{hasRun ? 'Compare three estimated round trips.' : 'Choose a run from your current city.'}</p></div>
    {!hasRun ? <>
      <div className="ready-facts"><div className="fact-icon"><Icon name="truck"/></div><div><strong>Dry van</strong><span>{data.boardCount} simulated loads available</span></div></div>
      <div className="ready-facts"><div className="fact-icon"><Icon name="wallet"/></div><div><strong>{state === 'unavailable' ? 'Unavailable' : money(run.cash.starting_balance)} starting cash</strong><span>Seeded Capital One sandbox balance</span></div></div>
      {state === 'loading' ? <div className="message neutral" role="status"><strong>Finding runs…</strong><p>Loading-state preview. No request is running.</p><button className="text-action" onClick={() => show('shortfall')}>Show sample results</button></div> : state === 'error' || state === 'unavailable' ? <div className="message warning" role="alert"><strong>{state === 'error' ? 'Couldn’t load runs' : 'Bank data unavailable'}</strong><p>{state === 'error' ? 'Your settings are unchanged. Try again.' : 'A missing balance isn’t a zero balance. Retry to show the sample data.'}</p></div> : <div className="planning-note">Compare up to three loads, empty miles, fuel, and the drive home.</div>}
      <button className="primary full" disabled={state === 'loading'} onClick={() => show('shortfall')}>{state === 'error' || state === 'unavailable' ? 'Try again' : 'Plan run'}<Icon name="arrow" size={18}/></button>
      <p className="footnote centered">No bank changes. This is a design preview.</p>
    </> : <>
      <div className="run-selector" role="group" aria-label="Select a run">{data.runs.map((r, i) => <button key={i} aria-pressed={selected === i} className={selected === i ? 'chosen' : ''} onClick={() => selectRun(i)}><span>{i === 0 ? 'Best net' : `Run ${i + 1}`}</span><strong>{money(r.chain.total_net_profit)}</strong></button>)}</div>
      <section className="earnings" aria-label="Run earnings"><div className="earnings-label"><span>Net profit</span><span className="subtle-tag">After costs</span></div><div className="big-number">{money(run.chain.total_net_profit)}</div><div className="earning-meta"><span>{money(run.chain.net_per_day)}<small> per day</small></span><span>{run.chain.days.toFixed(1)} days <b>·</b> {run.chain.total_miles.toFixed(0)} mi</span></div></section>
      <section className={`funding ${hasCash ? cash.shortfall ? 'shortfall' : 'covered' : 'unknown'}`} aria-label="Cash flow"><div className="funding-title"><Icon name={hasCash && !cash.shortfall ? 'check' : 'wallet'} size={18}/><h2>{!hasCash ? 'Cash flow' : cash.shortfall ? 'Cash shortfall' : 'Run covered'}</h2>{hasCash && <span>{day(cash.lowest_balance_date)}</span>}</div>
        {hasCash ? <><div className="funding-value">{money(cash.lowest_balance)}<span>lowest projected balance</span></div><p>{cash.shortfall ? 'Bills and fuel leave before broker payments arrive.' : 'Projected balance stays above zero during this run.'}</p></> : <p>Check fuel, bills, and payment dates before committing.</p>}
        {!hasCash ? <button className="primary full" onClick={() => show('shortfall')}>Check cash flow</button> : cash.shortfall && offer ? <button className="primary full" onClick={() => show('confirmation')}>Review advance <span>{money(offer.fee)} fee</span></button> : cash.shortfall ? <p>An advance does not cover this run. Choose a different option.</p> : <div className="success-note"><Icon name="check" size={16}/>{state === 'success' ? 'Advance preview applied' : 'No advance needed'}</div>}
        {state === 'success' && <p className="preview-receipt">Preview only. No deposit or repayment bill created.</p>}
      </section>
      <section className="stops"><div className="section-title"><h2>Route</h2><span>{run.chain.loads.length} loads · home at the end</span></div><ol>{run.chain.loads.map((id, i) => { const l = data.loads.find(x => x.id === id)!; return <li key={id}><span className="stop-number">{i+1}</span><div><strong>{l.origin.city.split(',')[0]} <span className="to">to</span> {l.destination.city.split(',')[0]}</strong><span>{id} · {l.broker}</span></div></li>; })}</ol></section>
      {hasCash && <details className="disclosure"><summary>Cash-flow events <span>{cash.timeline.length}</span></summary><div className="event-list">{cash.timeline.map((e, i) => <div className="event-row" key={i}><div><strong>{String(e.label)}</strong><span>{day(String(e.date))}</span></div><div><strong>{money(Number(e.amount))}</strong><span>{money(Number(e.balance))} balance</span></div></div>)}</div></details>}
      <details className="disclosure"><summary>Assumptions and data</summary><p>Seeded sandbox data. Financial states are generated by the existing backend. Road miles and map connections are estimates. Simplified hours-of-service rules.</p>{run.chain.feasible_notes.map((n,i) => <p key={i}>{n}</p>)}<p>After-trip broker payments are excluded from the trip balance.</p></details>
      <button className="text-action full" onClick={() => show('ready')}>Start a new plan</button>
    </>}
  </>;
  return <div className="mw-app">
    <div className="sr-only" role="status" aria-live="polite">{announcement}</div>
    <header className="topbar"><a href="./preview.html" className="brand" aria-label="LoadCheck preview home"><span className="brand-symbol"><Icon name="route" size={22}/></span>LoadCheck</a><nav aria-label="Main navigation"><button className="active" aria-current="page" onClick={() => show('ready')}>Runs</button><button onClick={() => setInfo(true)}>Check a load</button><button onClick={() => setInfo(true)}>Truck settings</button></nav><span className="preview-label"><i/> Local preview</span></header>
    <main aria-label="Run planning preview">
      <div className="map-stage" aria-label="Route map">
        <MapContainer center={[37.271, -79.9414]} zoom={8} zoomControl={false} scrollWheelZoom={false} zoomAnimation={false} fadeAnimation={false} markerZoomAnimation={false}>
          <MapTiles offline={tilesUnavailable} onOffline={() => setTilesUnavailable(true)} />
          <ZoomControl position="topright"/>
          {hasRun && (hasCash ? cash.route : run.cash.route).map((r,i) => <Polyline key={`${selected}-${i}`} positions={[r.from,r.to]} pathOptions={{color: hasCash ? balanceColor(r.balance) : '#2479dc',weight: 5,opacity: .95,dashArray: r.loaded ? undefined : '7 9'}}><Popup>{hasCash ? `${money(r.balance)} projected balance` : 'Cash flow not checked'} · {r.loaded ? 'Loaded' : 'Empty'}<br/>{day(r.start)}</Popup></Polyline>)}
          <Marker position={[37.271,-79.9414]} icon={divIcon({className:'home-marker',html:'<span>H</span>',iconSize:[44,44]})}><Popup>Roanoke, VA · Home base<br/>City-level location</Popup></Marker>
          {hasRun && run.chain.loads.map((id,i) => {const l=data.loads.find(x=>x.id===id)!;return <Marker key={id} position={[l.destination.lat!,l.destination.lng!]} icon={divIcon({className:'route-marker',html:`<span>${i+1}</span>`,iconSize:[44,44]})}><Tooltip permanent direction="bottom">{l.destination.city}</Tooltip><Popup>Stop {i+1} · {l.destination.city}</Popup></Marker>;})}
          <FitMap chain={hasRun ? run.chain : undefined} mobile={mobile} recenter={recenter}/>
        </MapContainer>
      </div>
      <div className="map-caption"><Icon name="pin" size={16}/><span>{hasRun ? 'Southeast · Estimated route' : 'Roanoke, Virginia'}</span></div>
      <button className="recenter icon-button" onClick={() => setRecenter(x=>x+1)} aria-label="Fit route to map"><Icon name="layers"/></button>
      {tilesUnavailable && <div className="map-offline" role="status">Offline map · city locations and estimated route. <button onClick={() => setTilesUnavailable(false)}>Retry tiles</button></div>}
      {!mobile && <aside className="trip-panel" aria-label="Trip planner" aria-busy={state === 'loading'}>{panel()}</aside>}
      <div className="map-legend" aria-label="Map legend">{hasRun && hasCash ? <><span><i className="green"/>Balance ≥ $500</span><span><i className="amber"/>$0–$499</span><span><i className="red"/>Overdrawn</span></> : <span>Plan a run to compare your route and costs.</span>}<small>Simulated loads · Nessie sandbox</small></div>
      {mobile && <section className="compact-sheet" aria-label="Trip summary" aria-busy={state === 'loading'}><div className="sheet-handle" aria-hidden="true"/><div className="compact-heading"><div><span className="eyebrow">{hasRun ? 'NET PROFIT' : 'STARTING FROM'}</span><h1>{hasRun ? money(run.chain.total_net_profit) : 'Roanoke, VA'}</h1></div><button ref={expandButton} className="expand-button" aria-haspopup="dialog" aria-expanded={expanded} onClick={()=>setExpanded(true)}>Expand<Icon name="chevron" size={16}/></button></div><p>{hasRun ? `${run.chain.days.toFixed(1)} days · ${run.chain.total_miles.toFixed(0)} miles · ${hasCash ? cash.shortfall ? 'Cash shortfall' : 'Run covered' : 'Check cash flow'}` : `${data.boardCount} simulated loads · ${state === 'unavailable' ? 'Unavailable' : money(run.cash.starting_balance)} starting cash`}</p><button className="primary full" onClick={()=>{if(!hasRun)show('shortfall');setExpanded(true);}}>{hasRun ? 'View run and cash flow' : 'Plan run'}<Icon name="arrow" size={18}/></button><small>Local preview · no bank transactions</small></section>}
    </main>
    <div className="preview-tools"><button aria-pressed={tilesUnavailable} onClick={() => setTilesUnavailable(x=>!x)}>Offline map</button><label htmlFor="preview-state">Preview state</label><select id="preview-state" value={state} onChange={e=>show(e.target.value as State)}>{(['ready','planned','shortfall','confirmation','success','loading','error','unavailable'] as State[]).map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select><button onClick={()=>{setSelected(0);show('ready');setExpanded(false);}}>Reset</button></div>
    <Modal open={mobile && expanded} onClose={collapse} title="Trip details" className="mobile-sheet"><button className="collapse-button" onClick={collapse}>Collapse to map</button>{panel()}</Modal>
    <Modal open={state==='confirmation'} onClose={()=>show('shortfall')} title="Confirm advance" className="advance-modal">
      {offer && <><span className="modal-symbol"><Icon name="wallet" size={28}/></span><p className="modal-intro">Capital One sandbox · {offer.load_id}</p><div className="modal-amount">{money(offer.amount)}</div><p className="centered muted">Projected deposit on {day(offer.on)}</p><dl className="terms"><div><dt>Advance fee</dt><dd>{money(offer.fee)}</dd></div><div><dt>Repayment</dt><dd>{money(offer.repay_amount)}</dd></div><div><dt>Repaid when broker pays</dt><dd>{day(offer.repay_on)}</dd></div></dl><p className="preview-warning">Design preview only. Confirming shows a sample result. No money moves and no Nessie records are created.</p><button className="primary full" onClick={()=>show('success')}>Confirm preview</button><button className="text-action full" onClick={()=>show('shortfall')}>Cancel</button></>}
    </Modal>
    <Modal open={info} onClose={()=>setInfo(false)} title="One-screen design preview"><p className="modal-intro">This preview focuses on Runs. Load checking and truck settings remain in the existing app and will be restyled after you approve this direction.</p><button className="primary full" onClick={()=>setInfo(false)}>Back to preview</button></Modal>
  </div>;
}
